# Script to perform VIIRS 2013 extractions 
apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-ssl-first-eval-train
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/profxj/ulmo_nvidia:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "32Gi"
            ephemeral-storage: 50Gi
          limits:
            cpu: "2"
            memory: "32Gi"
            ephemeral-storage: 100Gi
            nvidia.com/gpu:  "1"  # See docs to exlude certain types
        command: ["/bin/bash", "-c"]
        args:
          - cd ulmo; 
            git fetch;
            git checkout refactor_cl; 
            git pull; 
            python setup.py develop;
            cd ulmo/runs/SSL/First;
            python -u ssl_first.py 1;
            #cd ..;
            #aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp foo s3://viirs --recursive --force;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
        gpu-type: "1080Ti"  # titan-xp
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
