# Script to perform VIIRS 2013 extractions 
apiVersion: batch/v1
kind: Job
metadata:
  name: erdong-llc-viirs-eval-log-probs #-debug
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/profxj/ulmo_nvidia:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"   
            memory: "8Gi"  # Needs to be large enough to slurp in the images
            ephemeral-storage: 50Gi
          limits:
            cpu: "4"
            memory: "16Gi"
            ephemeral-storage: 100Gi
            nvidia.com/gpu:  "1"  # See docs to exlude certain types
        command: ["/bin/bash", "-c"]
        args:
          - cd ulmo; 
            git fetch;
            git checkout llc_viirs_evaluation; 
            git pull; 
            yes | pip install umap healpy torchvision;
            cd ulmo/runs/EvalLogProbs/;
            python ../../scripts/eval_extension.py --model_dir s3://llc/Model_Ulmo/llc_uniform_test_10_percent_train/ --data_dir s3://llc/Model_Ulmo/llc_uniform_test_10_percent_train/LLC_uniform_test_preproc_split.h5 --bucket_name llc;
            python ../../scripts/eval_extension.py --model_dir s3://llc/Model_Ulmo/llc_uniform_test_10_percent_train/ --data_dir s3://llc/Model_Ulmo/llc_uniform_test_10_percent_train/LLC_uniform_test_preproc_split.h5 --bucket_name viirs;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
          - name: "PYTHONPATH"
            value: "/ulmo/"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
        gpu-type: "1080Ti"  # titan-xp
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
