apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-modis2-latents-2019
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/profxj/ulmo:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "16Gi"
            ephemeral-storage: 120Gi
          limits:
            cpu: "4"
            memory: "16Gi"
            ephemeral-storage: 150Gi
            nvidia:  "1"  # See docs to exlude certain types
        command: ["/bin/bash", "-c"]
        args:
          - cd tmp; mkdir foo; cd foo; mkdir Evaluations; ulmo_eval 2019,2019 std; aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp foo s3://test --recursive
#          - ulmo_eval 2003,2019 std  # Can you do multiple commands this way?
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
