apiVersion: batch/v1
kind: Job
metadata:
  name: erdong-modis-simclr-base
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/karlschwarz2021/modis_simclr:v6  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "32Gi"
            ephemeral-storage: 64Gi
          limits:
            cpu: "2"
            memory: "64Gi"
            ephemeral-storage: 72Gi
            nvidia.com/gpu:  "2"  # See docs to exlude certain types
            # https://ucsd-prp.gitlab.io/userdocs/running/gpu-pods/
        command: ["/bin/bash", "-c"]
        args:
          - aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp s3://modis-l2/PreProc/MODIS_2010_95clear_128x128_inpaintT_preproc_0.8valid.h5 /modis_simclr/experiments/datasets/modis_dataset/;
            cd ./modis_simclr;
            python ./train_modis.py;
            aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp /modis_simclr/experiments/SimCLR/modis_models/ s3://modis_l2/ --recursive;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
        gpu-type: "1080Ti"  # titan-xp
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
