# Script to perform LLC extractions
# kubectl exec -it pod-name -- /bin/bash
apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-llc-download-restart3
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: container
        image: localhost:30081/profxj/ulmo_nvidia:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "6Gi"
            ephemeral-storage: 32Gi
          limits:
            cpu: "2"
            memory: "12Gi"
            ephemeral-storage: 150Gi
            #nvidia.com/gpu:  "1"  # See docs to exlude certain types
            # https://ucsd-prp.gitlab.io/userdocs/running/gpu-pods/
        command: ["/bin/bash", "-c"]
        args:
          - cd ulmo; 
            git fetch;
            git checkout more_llc_downloads; 
            git pull; 
            python setup.py develop;
            pip install xmitgcm;
            pip install zarr;
            pip install aiohttp;
            pip install netcdf4;
            cd ../tmp; 
            mkdir foo; 
            cd foo; 
            python -u /ulmo/ulmo/runs/LLC/ssh/llc_ssh.py --task download --istart 1533;
            #cd ..;
            #aws --endpoint http://rook-ceph-rgw-nautiluss3.rook s3 cp foo s3://llc --recursive --force;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
        gpu-type: "1080Ti"  # titan-xp
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
